service: raschonline
runtime: python312

entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
env_variables:
  URL_FETCH_ALLOWLIST: "raschonline-dot-taaacoword2512.df.r.appspot.com,www.healthup.org.tw,www.winsteps.com,winsteps.com,www,raschonline.com"
  URL_FETCH_MAX_BYTES: "10485760"   # 10MB
  URL_FETCH_TIMEOUT: "12"           # seconds

