# Base image: Windows Server Core with IIS
FROM mcr.microsoft.com/windows/servercore/iis

# Enable ASP feature
RUN powershell -Command Add-WindowsFeature Web-ASP

# Copy your site into IIS webroot
COPY . C:/inetpub/wwwroot

# Expose port 80 for HTTP
EXPOSE 80

# Start IIS service
ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]
